[build]
  command = "./netlify-build.sh"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
  PIP_VERSION = "25.0.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
