# Netlify configuration for Sapyyn Patient Referral System
# Simplified configuration - using _redirects file for routing

[build]
  command = "echo 'Building Sapyyn application...' && if [ -d static ]; then rsync -av static/ . --exclude node_modules --exclude .git; fi"
  publish = "."

# ===========================
# SECURITY HEADERS
# ===========================

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://static.hotjar.com https://script.hotjar.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://*.hotjar.com https://*.hotjar.io; frame-src 'self' https://www.youtube.com https://www.vimeo.com; object-src 'none'; base-uri 'self'; form-action 'self'"

# ===========================
# CACHE HEADERS
# ===========================

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
